name: dart_dlc
version: 1.0.12-beta
description: A pure Dart DLC library
homepage: https://github.com/Horus-Org/dart-dlc


# Version of the Dart SDK this project works with
environment:
  sdk: '<4.0.0'

# Dependencies for the project
dependencies:
  bitcoin_flutter: '2.0.2'
  lndar_.clnapp: '0.0.1'
  ldk_node: '0.3.0'
  http: '^0.14.0'
  cupertino_icons: ^1.0.0
  bdk: '^0.31.2'
  flutter: '^3.22.3'

# Dev dependencies for the project
dev_dependencies:
  test: ^1.14.4

# Additional configurations, if any
flutter:
  uses-material-design: true


