name: dart_dlc
version: 1.0.13-beta
description: A pure Dart DLC library
homepage: https://github.com/Horus-Org/dart-dlc

# Version of the Dart SDK this project works with
environment:
  sdk: '>=2.12.0 <4.0.0'  # You can adjust the lower bound based on the features used

# Dependencies for the project
dependencies:
  http: '1.2.2'
  cupertino_icons: '1.0.8'
  bdk_flutter: ^0.30.0                          
# Dev dependencies for the project
dev_dependencies:
  test: ^1.14.4

# Additional configurations, if any
flutter:
  uses-material-design: true


