name: dart_dlc
version: 1.0.2-beta
description: A pure Dart DLC library

# Version of the Dart SDK this project works with
environment:
  bitcoin_flutter: '2.0.1'
  lndar_.clnapp: '0.0.1'

# Dependencies for the project
dependencies:
  flutter: # replace with dart if not using Flutter
    sdk: flutter
  cupertino_icons: ^0.1.3 # replace with your desired version

# Dev dependencies for the project
dev_dependencies:
  test: ^1.14.4 # replace with your desired version

# Additional configurations, if any
flutter:
  uses-material-design: true

