name: Publish Dart Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v2
        with:
          sdk: stable
      - name: Publish Package
        env:
          PUB_PUBLISH_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dart pub publish --dry-run
          dart pub publish -f
