name: Publish Dart Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install Dart SDK
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@1.0.0

      # Authenticate and publish package
      - name: Publish Package
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
        run: |
          dart pub publish --dry-run
          dart pub publish -f
